# 14_Statistics_in_ML

### How is Statistics used in Machine Learning?

Statistics powers nearly every stage of a machine learning pipeline — from cleaning raw data to training and evaluating models. Below is how statistics shows up in each core ML step.

## 01. Data Cleaning

Data cleaning uses statistics to spot invalid, inconsistent, or corrupted values before analysis.

**Example:**
Finding a negative "age" value in a customer dataset.

**How Statistics Helps:**
Uses summary statistics (mean, min, max, count) to profile and flag abnormal values.

In [1]:
import pandas as pd
data = pd.DataFrame({'age':[25,32,-5,40,29,150,35]})
print(data.describe())

              age
count    7.000000
mean    43.714286
std     49.097570
min     -5.000000
25%     27.000000
50%     32.000000
75%     37.500000
max    150.000000


**Interpretation**: The min (-5) and max (150) values immediately reveal invalid ages that need correction.

## 02. Missing Value Handling

Missing value handling fills gaps in data using statistically sound estimates instead of guesses.

**Example:**
Filling missing patient age values with the median age.

**How Statistics Helps:**
Uses mean, median, or mode to impute missing values based on the feature's distribution.

In [2]:
import numpy as np
import pandas as pd
data = pd.DataFrame({'age':[25,32,np.nan,40,29,np.nan,35]})
data['age_filled'] = data['age'].fillna(data['age'].median())
print(data)

    age  age_filled
0  25.0        25.0
1  32.0        32.0
2   NaN        32.0
3  40.0        40.0
4  29.0        29.0
5   NaN        32.0
6  35.0        35.0


**Interpretation**: The missing values are replaced with the median age, keeping the distribution realistic.

## 03. Outlier Detection

Outlier detection finds data points that deviate sharply from the rest, which can distort model training.

**Example:**
Flagging a ₹700 transaction among typical ₹200 transactions.

**How Statistics Helps:**
Uses IQR or Z-score to define a normal range and flag values outside it.
    

In [3]:
import numpy as np
data = np.array([200,210,195,205,215,700,208,202])
q1 = np.percentile(data,25)
q3 = np.percentile(data,75)
iqr = q3-q1
lower = q1-1.5*iqr
upper = q3+1.5*iqr
print(data[(data<lower)|(data>upper)])

[700]


**Interpretation**: 700 is correctly flagged as an outlier, falling well outside the IQR bounds.

## 04. Feature Engineering

Feature engineering creates new, more useful variables from existing raw data.

**Example:**
Creating "average order value" from total spend and order count.

**How Statistics Helps:**
Uses ratios, aggregates (mean, sum), and binning to derive meaningful predictors.

In [4]:
import pandas as pd
data = pd.DataFrame({'customer':['A','B','C'],'total_spend':[5000,12000,3000],'num_orders':[10,15,5]})
data['avg_order_value'] = data['total_spend']/data['num_orders']
print(data)

  customer  total_spend  num_orders  avg_order_value
0        A         5000          10            500.0
1        B        12000          15            800.0
2        C         3000           5            600.0


**Interpretation**: Customer B has the highest average order value, a pattern not visible from raw totals alone.

## 05. Feature Scaling

Feature scaling rescales features so no single feature dominates due to its magnitude.

**Example:**
Scaling income (in thousands) and age (in years) to comparable ranges.

**How Statistics Helps:**
Uses mean and standard deviation (standardization) or min/max (normalization) to rescale values.

In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler
income = np.array([50000,62000,58000,71000,49000,54000]).reshape(-1,1)
scaled = StandardScaler().fit_transform(income)
print(scaled.flatten())

[-0.96943583  0.61691371  0.08813053  1.80667586 -1.10163162 -0.44065265]


**Interpretation**: After scaling, income is centered around 0 with unit variance, making it comparable to other features.

## 06. Data Normalization

Data normalization rescales values into a fixed range, commonly [0,1].

**Example:**
Scaling image pixel values (0–255) to [0,1] for a neural network.

**How Statistics Helps:**
Uses min and max statistics to proportionally rescale every value.

In [6]:
import numpy as np
pixels = np.array([0,64,128,192,255])
normalized = (pixels-pixels.min())/(pixels.max()-pixels.min())
print(normalized)

[0.         0.25098039 0.50196078 0.75294118 1.        ]


**Interpretation**: Pixel values are rescaled into [0,1] while preserving their relative spacing.

## 07. Model Evaluation

Model evaluation measures how well predictions match actual outcomes.

**Example:**
Checking a weather model's RMSE between predicted and actual temperatures.

**How Statistics Helps:**
Uses metrics like RMSE, R², accuracy, and precision to quantify prediction error.

In [7]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
y_true = np.array([50,55,60,65,70])
y_pred = np.array([52,54,63,64,68])
print(np.sqrt(mean_squared_error(y_true,y_pred)))
print(r2_score(y_true,y_pred))

1.9493588689617927
0.924


**Interpretation**: Low RMSE and high R² show the model's predictions closely match actual values.

## 08. Linear Regression

Linear Regression predicts a continuous value based on one or more input variables.

**Example:**
Predicting house price from square footage.

**How Statistics Helps:**
Uses least squares to find the line minimizing squared prediction errors.

In [8]:
import numpy as np
from sklearn.linear_model import LinearRegression
sqft = np.array([800,1000,1200,1500,1800,2000]).reshape(-1,1)
price = np.array([160000,200000,240000,300000,360000,400000])
model = LinearRegression().fit(sqft,price)
print(model.coef_)
print(model.intercept_)

[200.]
-5.820766091346741e-11


**Interpretation**: The coefficient shows a consistent price increase for every added square foot.

## 09. Logistic Regression

Logistic Regression predicts the probability of a binary outcome.

**Example:**
Predicting whether a customer will churn (yes/no).

**How Statistics Helps:**
Uses maximum likelihood estimation and the sigmoid function to model probabilities.

In [9]:
import numpy as np
from sklearn.linear_model import LogisticRegression
usage_hours = np.array([1,2,3,8,9,10,2,7]).reshape(-1,1)
churn = np.array([1,1,1,0,0,0,1,0])
model = LogisticRegression().fit(usage_hours,churn)
print(model.predict_proba([[3],[9]]))

[[0.10477256 0.89522744]
 [0.98158749 0.01841251]]


**Interpretation**: A customer with fewer usage hours has a much higher predicted probability of churning.

## 10. Naive Bayes

Naive Bayes classifies data using probability, assuming features are independent.

**Example:**
Classifying an email as spam or not spam.

**How Statistics Helps:**
Uses Bayes' Theorem to compute the probability of each class given the input features."

In [10]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
word_freq = np.array([[5,0],[6,1],[1,5],[0,6],[4,0],[1,4]])
label = np.array([0,0,1,1,0,1])
model = GaussianNB().fit(word_freq,label)
print(model.predict([[5,1],[1,5]]))

[0 1]


**Interpretation**: The model correctly classifies each pattern based on learned class probabilities.

## 11. Clustering

Clustering groups similar data points together without predefined labels.

**Example:**
Segmenting customers by spend and purchase frequency.

**How Statistics Helps:**
Uses distance and variance (K-Means minimizes within-cluster variance) to form groups.

In [11]:
import numpy as np
from sklearn.cluster import KMeans
np.random.seed(42)
spend = np.random.normal(500,100,30)
frequency = np.random.normal(10,3,30)
data = np.column_stack([spend,frequency])
model = KMeans(n_clusters=2,random_state=42,n_init=10).fit(data)
print(model.cluster_centers_)

[[423.46081002   9.73021372]
 [567.77206101   9.4959609 ]]


**Interpretation**: The two cluster centers represent distinct customer segments with different spend and frequency patterns.

## 12. Principal Component Analysis (PCA)

PCA reduces the number of features while preserving as much information as possible.

**Example:**
Reduce a dataset with 20 features to 5 principal components.

**How Statistics Helps:**
Uses variance, covariance, and eigenvalues to identify the most informative components.

In [12]:
import numpy as np
from sklearn.decomposition import PCA
np.random.seed(42)
f1 = np.random.normal(0,1,100)
f2 = f1*0.8+np.random.normal(0,0.3,100)
f3 = np.random.normal(0,1,100)
data = np.column_stack([f1,f2,f3])
pca = PCA(n_components=2).fit(data)
print(pca.explained_variance_ratio_)

[0.58642791 0.39406568]


**Interpretation**: Most of the data's spread is captured along PC1, showing fewer dimensions retain most of the original variance.

## 13. Recommendation Systems

Recommendation systems suggest items based on similarity between users or items.

**Example:**
Recommending movies based on similar viewing history to other users.

**How Statistics Helps:**
Uses similarity measures like cosine similarity or correlation to find matching patterns.

In [13]:
import numpy as np
from numpy.linalg import norm
user_a = np.array([5,3,0,1,4])
user_b = np.array([4,0,0,1,5])
similarity = np.dot(user_a,user_b)/(norm(user_a)*norm(user_b))
print(similarity)

0.8858784221879579


**Interpretation**: The high similarity score suggests User A and User B have closely matching preferences, so recommendations can be shared between them.

## Overall Advantages and Limitations of Statistics in Machine Learning

### Advantages
1. Provides the mathematical foundation for nearly every ML step, from cleaning data to evaluating final models.
2. Enables objective, quantifiable decisions instead of arbitrary choices.
3. Statistical evaluation metrics allow fair comparison between different models.
4. Techniques like PCA and clustering rely on well-established statistical theory, making their behavior interpretable.
5. Statistical significance testing helps validate whether an effect is real or due to chance.

### Limitations
1. Many methods assume normally distributed or well-behaved data, which real-world data often violates.
2. Over-reliance on fixed thresholds (1.5×IQR, p<0.05) can ignore domain context.
3. Techniques like PCA and scaling can reduce interpretability of features.
4. Correlation and similarity-based methods can miss non-linear relationships.
5. Assumptions like independence (Naive Bayes) or linearity (regression) are often violated in practice.

## Interview Questions & Answers

**1. Where does statistics play a role before any model is even trained?**
In data cleaning, missing value imputation, outlier detection, feature engineering, and scaling — all rely on descriptive statistics like mean, median, and quartiles.

**2. How does linear regression rely on statistical theory?**
It estimates coefficients using least squares, derived from minimizing error variance, and uses p-values to test predictor significance.

**3. What statistical principle underlies PCA?**
PCA uses the covariance matrix's eigenvectors/eigenvalues to find directions of maximum variance for dimensionality reduction.

**4. Why does feature scaling matter for some algorithms but not others?**
Distance and gradient-based models (KNN, SVM, neural nets) are affected by feature magnitude, while tree-based models are scale-invariant.

**5. How is statistics used to evaluate a trained model?**
Through metrics like RMSE, R², accuracy, and precision, plus cross-validation to statistically estimate generalization.

**6. What statistical assumption does Naive Bayes make?**
It assumes features are conditionally independent given the class label, which is often unrealistic but still works well in practice.

**7. How does clustering use statistics to group data?**
It uses distance measures (like Euclidean distance) and minimizes within-cluster variance to form groups of similar points.

## Self-Reflection

Working through this notebook helped me see statistics not as separate from machine learning, but as its underlying engine — every ML step, from preprocessing to model evaluation, is grounded in statistical concepts like variance, probability, and distance. The key insight I take away is that even core algorithms like linear regression, logistic regression, and Naive Bayes are statistical models at their heart, not black boxes. This connects directly to real ML workflows, where strong statistical foundations are what separate a reliable pipeline from one that silently produces poor predictions.